---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: lint
    image: golangci/golangci-lint:v1.39.0
    commands:
      - golangci-lint run --no-config -v --timeout 10m ./...

  - name: test
    image: golang:1.16
    commands:
      - go test -coverprofile cover.out -v ./...
      - go tool cover -func cover.out
  - name: build
    image: plugins/docker
    settings:
      repo: registry.megpoid.xyz/swarm-updater
      tags: latest
      registry: registry.megpoid.xyz
      mirror: http://mirror:5000
      build_args:
        - CI_TAG=${DRONE_TAG}
        - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
        - BUILD_COMMIT_SHORT=${DRONE_COMMIT_SHA:0:8}
        - CI_BUILD_CREATED=${DRONE_BUILD_CREATED}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  branch:
    - master
